mensagem = {
    '0': 'Operacao executada com sucesso',
    '1': 'Operacao de pagamento em andamento',
    '2': 'Operacao de pagamento nao concluida',
    '3': 'Operacao registrada, aguarde o pagamento',
    '90000': 'Forma de pagamento invalida',
    '90001': 'Tempo excedido operacao interrompida',
    '90002': 'Erro ao montar os dados de retorno',
    '90003': 'Nao foi possivel inicializar o executavel',
    '90004': 'Nao foi possivel estabelecer a conexao com o servidor, indiponivel ou multiplas sessoes abertas',
    '90005': 'Nao foi possivel obter os dados de pagamento',
    '90006': 'Refazer transacao operacao interrompida',
    '64001': 'Parâmetro 1 inválido',
    '64002': 'Parâmetro 2 inválido',
    '64003': 'Parâmetro 3 inválido',
    '64004': 'Parâmetro 4 inválido',
    '64005': 'Parâmetro 5 inválido',
    '64257': 'Não foi possível criar a thread na coleta de dados',
    '64258': 'Erro na montagem do serviço pela API',
    '64259': 'Erro ao verificar mensagem mensagem inválida',
    '64260': 'Erro ao montar mensagem',
    '64261': 'Erro no arquivo de controle da TEF',
    '64262': 'Erro no contexto do arquivo de TEF(não mais utilizado)',
    '64263': 'Erro na totalização de TEF',
    '64264': 'Erro no arquivo de controle utilizado finalização no ciclo multi-TEF',
    '64265': 'Estourou o número máximo de TEF numa sessão multi-TEF',
    '64266': 'Não salvou a mensagem de confirmação para o SAB',
    '64267': 'Não salvou a mensagem de desfazimento para o SAB',
    '64268': 'Erro no processo de criptografia entre Client-Server',
    '65024': 'A transação em andamento a aplicação deve aguardar',
    '65025': 'SCOPE API não foi inicializada corretamente',
    '65026': 'SCOPE API já foi inicializada corretamente',
    '65027': 'Existe transação suspensa',
    '65028': 'Não existe transação suspensa',
    '65029': 'API ainda não fez nenhuma transação após a inicialização. A aplicação está tentando obter um handle sem ter feito nenhuma transação desde última conexão com o ScopeSRV',
    '65030': 'Logon duplicado',
    '65031': 'Protocolo não suportado SCOPE Client com versão de protocolo superior ao SCOPE Server',
    '65032': 'POS não cadastrado',
    '65033': 'Servidor não configurado no arquivo scope.ini',
    '65034': 'Não há mais PDVs disponíveis. Erro retornado quando a aplicação passa o caractere como PDV para que o SCOPE Server lhe dê um número de PDV válido, mas não há mais PDVs disponíveis',
    '65035': 'Protocolo incompatível SCOPE Client com versão de protocolo extremamente antigo(P00, P01 ou P02).',
    '65036': 'Não pode mais desfazer uma transação que já iniciou o ciclo de finalização – situação que pode ocorrer apos queda de energia ou na inicialização da aplicação.',
    '65037': 'Não há arquivo com dados da transação anterior salvo',
    '65280': 'ScopeSrv off-line ou o IP configurado no arquivo scope.ini está apontando para a máquina errada',
    '65281': 'Instituição off-line',
    '65282': 'Transação cancelada pelo operador ou no caso de um estorno via REDE: estorno fora do prazo permitido, validade não confere.',
    '65283': 'Serviço ou BIN não configurado',
    '65284': 'Transação já foi cancelada',
    '65285': 'Transação não encontrada',
    '65286': 'Transação não permite cancelamento',
    '65287': 'Dados informados não conferem com a transação original',
    '65288': 'Erro no acesso ao banco de dados',
    '65289': 'Time-out no acesso ao banco de dados',
    '65290': 'Banco de dados off-line',
    '65291': 'Transação abortada pelo aplicativo',
    '65292': 'Transação não implementada',
    '65293': 'Handle inválido(ver Obtendo handle)',
    '65294': 'Taxa de serviço é inválida',
    '65295': 'Taxa de serviço excede limite',
    '65296': 'Dado inválido',
    '65297': 'Não existe cupom válido',
    '65298': 'Área reservada para o buffer é insuficiente para o SCOPE Client preencher com os dados solicitados',
    '65299': 'Limite inválido inferior ao permitido',
    '65300': 'Transação desfeita',
    '65301': 'Digitação não permitida',
    '65302': 'Memória insuficiente',
    '65303': '“Service Code” inválido',
    '65304': 'Data inválida',
    '65305': 'Cartão vencido',
    '65306': 'Cartão inválido',
    '65307': 'Desfazimento não disponível',
    '65308': 'Erro na impressão do cupom',
    '65309': 'Sessão em andamento – a transação solicitada deve ser única numa sessão de TEF, ou seja, não pode ser chamada se há transações na sessão de TEF atual',
    '65310': 'Transação já efetuada',
    '65311': 'Inserir chip do cartão',
    '65312': 'Controle obrigatório',
    '65313': 'Pré-autorização obrigatória',
    '65314': 'Serviço não configurado',
    '65315': 'Serviço não definido',
    '65316': 'Número de parcelas inválidas',
    '65317': 'Valor inválido',
    '65318': 'Serviço ou BIN não configurado para Visanet',
    '65319': 'Estado de coleta não definido',
    '65320': 'Operação não permitida',
    '65321': 'CNPJ/CPF inválido',
    '65322': 'Primeiro bloco do código de barras está inválido',
    '65323': 'Segundo bloco do código de barras está inválido',
    '65324': 'Terceiro bloco do código de barras está inválido',
    '65325': 'Quarto bloco do código de barras está inválido',
    '65326': 'Dados adicionais AID do chip do cartão inexistente',
    '65328': 'Autorizador retornou dados inválidos',
    '65329': 'Conta não permitida',
    '65330': 'Conta vencida',
    '65331': 'Não existe resumo',
    '65332': 'Código de barra inválido',
    '65333': 'Erro na consistência do DAC',
    '65334': 'Erro no envio da confirmação ou desfazimento da transação anterior',
    '65335': 'Serviço invertido a aplicação está tentando fazer uma transação de débito com um cartão de crédito ou vice-versa',
    '65336': 'Cartão não permitido',
    '65337': 'Permitido somente a coleta do CPF consulta de cheque',
    '65338': 'Erro interno na execução da coleta',
    '65339': 'Lista(de produtos, de medicamentos, etc.) não está disponível.',
    '65340': 'Erro de leitura do cartão',
    '65341': 'Controle inválido',
    '65342': 'Erro ao enviar mensagem para o servidor',
    '65343': 'Interface SAB não inicializada',
    '65344': 'Erro: dados ainda não disponíveis(SAB)',
    '65345': 'Erro: dados indisponíveis(SAB)',
    '65346': 'Servidor SAB off-line',
    '65347': 'Erro de conexão entre SCOPE e SAB',
    '65348': 'Erro no NSU recebido',
    '65349': 'Erro no logon do PDV',
    '65350': 'Erro no processamento do chip',
    '65351': 'Operadora inválida',
    '65352': 'Dados, da recarga de celular, não encontrados.',
    '65353': 'Transação cancelada pelo cliente',
    '65360': 'Transação aprovada off-line',
    '65361': 'Versão do banco de dados incompatível',
    '65362': 'Cancelamento fora do prazo permitido',
    '65363': 'Mensagem inválida',
    '65364': 'PIN-Pad não foi aberto',
    '65365': 'PIN-Pad já foi aberto a aplicação abriu o PIN-Pad antes de conectar ao ScopeSRV, mas não deveria ter-lo feito, pois no ScopeCNF está configurado com uso exclusivo do SCOPE',
    '65366': 'Estado inválido a aplicação está tentando obter os serviços',
    'veis ': 'um estado de coleta inadequado',
    '65367': 'PIN-Pad compartilhado não está configurado, mas a rede exige que seja compartilhado',
    '65368': 'PIN-Pad compartilhado não trabalha com a versão 2000 da VISA',
    '65369': 'Função de uso exclusivo na interface coleta',
    '65370': 'Área insuficiente para os atributos do serviço',
    '65371': 'O SCOPE está configurado para uso de PIN-Pad compartilhado, mas a aplicação informou que está com o kit Visanet para PIN-Pad',
    '65372': 'O SCOPE não está configurado para uso de PIN-Pad compartilhado, mas a aplicação informou que está com PIN-Pad compartilhado',
    '65373': 'Erro ao inicializar periféricos na interface HLAPI',
    '65374': 'Erro ao desmontar a estrutura ISO',
    '65375': 'Bandeira não está configurada',
    '65376': 'Função indisponível',
    '65377': 'Valor mínimo da parcela é inválido',
    '65378': 'Valor da consulta Vale Gás ainda não está disponível',
    '65379': 'Número de Telefone inválido',
    '65380': 'DDD inválido',
    '65381': 'Erro Rede Modelo 2',
    '65382': 'Erro Rede Modelo 3',
    '65383': 'Confirmação Positiva Inconsistente',
    '65384': 'Transação Offline Permitido apenas reimpressão offline',
    '65385': 'Contrato Suspenso',
    '65386': 'Transação permite somente digitado',
    '65387': 'Não Encontrado(para quando não veio menu dinâmico na carga de tabelas).',
    '65391': 'Erro ao acessar arquivo de contexto da PBM.',
    '65392': 'Ticket Car Placa Inválida',
    '65393': 'Correspondente Bancário Bradesco Consulta Não Habilitada Habilite a Consulta Pagamento no Perfil de Serviços',
    '65394': 'Código da Bandeira maior que 255.',
    '65395': 'Rede em processo de inicialização.',
    '65396': 'PINPad não suporta modo de multi-bandeira extendido',
    '65397': 'Erro na transação de Estatística Automática da rede Rede',
    '65398': 'PINPad com tabelas vazias. Verifique se todas as redes desta filial fizeram inicialização de tabelas com sucesso.',
    '65399': 'Contactless não habilitado na carga de tabelas pela rede em questão para este estabelecimento. No caso da Cielo a habilitação é na tabela 1B TerminalConfiguration.',
    '65400': 'Contactless não permitido. AID em questão não possui dados contactless habilitados na carga de tabelas.',
    '65401': 'Contactless sem produto habilitado pela rede em questão. No caso da Cielo o produto não está habilitado na tabela 7C GrupoRangeFuncao.',
    '65402': 'Excede limite contactless. No caso da Cielo esse limite está estabelecido na tabela 4ª RiscoContactless.',
    '65403': 'Modo Inválido Insira cartão com chip na leitora.',
    '65404': 'Fallback não permitido',
    '65405': 'Moeda inválida',
    '65406': 'Modo de entrada difere da transação original. Use o mesmo modo de entrada da transação original.',
    '65407': 'Documento inválido',
    '65408': 'Chamada à Função ScopeObtemTransacaoId não permitida. È permitida somente durante uma operação de crédito ou débito.',
    '65409': 'Valor máximo da parcela inválido.',
    '65410': 'Verificação do Perfil de Pagamento Recorrente negada.',
    '65411': 'Erro de alocação de memória na função ScopeObtemTransacaoId.',
    '65412': 'Token utilizado nas funções de Pagamento Recorrente inválido.',
    '65413': 'Cartão utilizado na função ScopeAlteraPreAutorizacaoCredito não corresponde ao utilizado na função ScopePreAutorizacaoCredito.',
    '65414': 'Coleta do Terminal Origem nas funções ScopeAlteraPreAutorizacaoCredito e ScopeCapturaPreAutorizacaoCredito obrigatória.',
    '65415': 'Pré-Autorização foi cancelada.',
    '65416': 'Pré-Autorização já foi confirmada.',
    '65417': 'Terminal Origem coletado nas funções ScopeAlteraPreAutorizacaoCredito e ScopeCapturaPreAutorizacaoCredito inválido.',
    '65418': 'Sem rede disponível para efetuar o débito para pagamento.',
    '65419': 'Contactless com valor zerado não permitido',
    '65420': 'Desconto não permitido',
    '65421': 'Produto não disponível',
    '65422': 'Erro na consulta dinâmica',
    '65535': 'Erro genérico',
    '5000':  'Erro desmontando o pacote recebido',
    '5001': 'Não achou a Master Key referente',
    '5002': 'Ocorreu timeout do pacote',
    '5003': 'Erro configurando o registrador',
    '5004': 'Parâmetro lib incorreto',
    '5005': 'Erro Leitura Cartao/Trilha',
}
